spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_company?useUnicode=true&serverTimezone=UTC
    username: root
    password: adminlyc
  jpa:
    show-sql: true
server:
  port: 8082

staffjoy:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"